# Generated by Django 5.1.1 on 2024-10-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersedes_sait_app', '0005_personaldata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='car_model',
            field=models.CharField(default='', max_length=100),
        ),
    ]
