# Generated by Django 5.1.1 on 2024-10-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersedes_sait_app', '0006_alter_product_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='car_model',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
