# Generated by Django 5.1.1 on 2024-10-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersedes_sait_app', '0010_alter_product_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='car_model',
            field=models.CharField(max_length=100),
        ),
    ]
