# Generated by Django 5.1.1 on 2024-10-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mersedes_sait_app', '0017_alter_product_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
